// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: notifications.proto

package notification

import (
	common "task_service/pb/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event int32

const (
	Event_CREATED   Event = 0
	Event_UPDATED   Event = 1
	Event_DELETED   Event = 2
	Event_ASSIGNED  Event = 3
	Event_CONCERNED Event = 4
	Event_MENTIONED Event = 5
	Event_DEADLINE  Event = 6
)

// Enum value maps for Event.
var (
	Event_name = map[int32]string{
		0: "CREATED",
		1: "UPDATED",
		2: "DELETED",
		3: "ASSIGNED",
		4: "CONCERNED",
		5: "MENTIONED",
		6: "DEADLINE",
	}
	Event_value = map[string]int32{
		"CREATED":   0,
		"UPDATED":   1,
		"DELETED":   2,
		"ASSIGNED":  3,
		"CONCERNED": 4,
		"MENTIONED": 5,
		"DEADLINE":  6,
	}
)

func (x Event) Enum() *Event {
	p := new(Event)
	*p = x
	return p
}

func (x Event) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Event) Descriptor() protoreflect.EnumDescriptor {
	return file_notifications_proto_enumTypes[0].Descriptor()
}

func (Event) Type() protoreflect.EnumType {
	return &file_notifications_proto_enumTypes[0]
}

func (x Event) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Event.Descriptor instead.
func (Event) EnumDescriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{0}
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Event         Event                  `protobuf:"varint,3,opt,name=event,proto3,enum=task_manager.notification.Event" json:"event,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Seen          bool                   `protobuf:"varint,5,opt,name=seen,proto3" json:"seen,omitempty"`
	Timestamp     string                 `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Notification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Notification) GetEvent() Event {
	if x != nil {
		return x.Event
	}
	return Event_CREATED
}

func (x *Notification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notification) GetSeen() bool {
	if x != nil {
		return x.Seen
	}
	return false
}

func (x *Notification) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type SendNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notification  *Notification          `protobuf:"bytes,1,opt,name=notification,proto3" json:"notification,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *SendNotificationRequest) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type NoticeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostedBy      string                 `protobuf:"bytes,1,opt,name=posted_by,json=postedBy,proto3" json:"posted_by,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoticeRequest) Reset() {
	*x = NoticeRequest{}
	mi := &file_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoticeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeRequest) ProtoMessage() {}

func (x *NoticeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeRequest.ProtoReflect.Descriptor instead.
func (*NoticeRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{2}
}

func (x *NoticeRequest) GetPostedBy() string {
	if x != nil {
		return x.PostedBy
	}
	return ""
}

func (x *NoticeRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NoticeRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type NoticeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *common.Response       `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	NoticeId      string                 `protobuf:"bytes,2,opt,name=notice_id,json=noticeId,proto3" json:"notice_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoticeResponse) Reset() {
	*x = NoticeResponse{}
	mi := &file_notifications_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoticeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeResponse) ProtoMessage() {}

func (x *NoticeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeResponse.ProtoReflect.Descriptor instead.
func (*NoticeResponse) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{3}
}

func (x *NoticeResponse) GetResponse() *common.Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *NoticeResponse) GetNoticeId() string {
	if x != nil {
		return x.NoticeId
	}
	return ""
}

type NoticeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NoticeId      string                 `protobuf:"bytes,1,opt,name=notice_id,json=noticeId,proto3" json:"notice_id,omitempty"`
	PostedBy      string                 `protobuf:"bytes,2,opt,name=posted_by,json=postedBy,proto3" json:"posted_by,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoticeEvent) Reset() {
	*x = NoticeEvent{}
	mi := &file_notifications_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoticeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeEvent) ProtoMessage() {}

func (x *NoticeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeEvent.ProtoReflect.Descriptor instead.
func (*NoticeEvent) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{4}
}

func (x *NoticeEvent) GetNoticeId() string {
	if x != nil {
		return x.NoticeId
	}
	return ""
}

func (x *NoticeEvent) GetPostedBy() string {
	if x != nil {
		return x.PostedBy
	}
	return ""
}

func (x *NoticeEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NoticeEvent) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *NoticeEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_notifications_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{5}
}

func (x *WatchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetNotifRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotifRequest) Reset() {
	*x = GetNotifRequest{}
	mi := &file_notifications_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotifRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotifRequest) ProtoMessage() {}

func (x *GetNotifRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotifRequest.ProtoReflect.Descriptor instead.
func (*GetNotifRequest) Descriptor() ([]byte, []int) {
	return file_notifications_proto_rawDescGZIP(), []int{6}
}

func (x *GetNotifRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_notifications_proto protoreflect.FileDescriptor

const file_notifications_proto_rawDesc = "" +
	"\n" +
	"\x13notifications.proto\x12\x19task_manager.notification\x1a\fcommon.proto\"\xc4\x01\n" +
	"\fNotification\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x126\n" +
	"\x05event\x18\x03 \x01(\x0e2 .task_manager.notification.EventR\x05event\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x12\n" +
	"\x04seen\x18\x05 \x01(\bR\x04seen\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\tR\ttimestamp\"f\n" +
	"\x17SendNotificationRequest\x12K\n" +
	"\fnotification\x18\x01 \x01(\v2'.task_manager.notification.NotificationR\fnotification\"V\n" +
	"\rNoticeRequest\x12\x1b\n" +
	"\tposted_by\x18\x01 \x01(\tR\bpostedBy\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\"h\n" +
	"\x0eNoticeResponse\x129\n" +
	"\bresponse\x18\x01 \x01(\v2\x1d.task_manager.common.ResponseR\bresponse\x12\x1b\n" +
	"\tnotice_id\x18\x02 \x01(\tR\bnoticeId\"\x8f\x01\n" +
	"\vNoticeEvent\x12\x1b\n" +
	"\tnotice_id\x18\x01 \x01(\tR\bnoticeId\x12\x1b\n" +
	"\tposted_by\x18\x02 \x01(\tR\bpostedBy\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\"'\n" +
	"\fWatchRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"*\n" +
	"\x0fGetNotifRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId*h\n" +
	"\x05Event\x12\v\n" +
	"\aCREATED\x10\x00\x12\v\n" +
	"\aUPDATED\x10\x01\x12\v\n" +
	"\aDELETED\x10\x02\x12\f\n" +
	"\bASSIGNED\x10\x03\x12\r\n" +
	"\tCONCERNED\x10\x04\x12\r\n" +
	"\tMENTIONED\x10\x05\x12\f\n" +
	"\bDEADLINE\x10\x062\xba\x03\n" +
	"\x13NotificationService\x12e\n" +
	"\x10SendNotification\x122.task_manager.notification.SendNotificationRequest\x1a\x1d.task_manager.common.Response\x12h\n" +
	"\x11PostToNoticeBoard\x12(.task_manager.notification.NoticeRequest\x1a).task_manager.notification.NoticeResponse\x12e\n" +
	"\x10WatchNoticeBoard\x12'.task_manager.notification.WatchRequest\x1a&.task_manager.notification.NoticeEvent0\x01\x12k\n" +
	"\x12GetMyNotifications\x12*.task_manager.notification.GetNotifRequest\x1a'.task_manager.notification.Notification0\x01B@Z>github.com/Sourav-126/distributed-task-manager/pb/notificationb\x06proto3"

var (
	file_notifications_proto_rawDescOnce sync.Once
	file_notifications_proto_rawDescData []byte
)

func file_notifications_proto_rawDescGZIP() []byte {
	file_notifications_proto_rawDescOnce.Do(func() {
		file_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notifications_proto_rawDesc), len(file_notifications_proto_rawDesc)))
	})
	return file_notifications_proto_rawDescData
}

var file_notifications_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_notifications_proto_goTypes = []any{
	(Event)(0),                      // 0: task_manager.notification.Event
	(*Notification)(nil),            // 1: task_manager.notification.Notification
	(*SendNotificationRequest)(nil), // 2: task_manager.notification.SendNotificationRequest
	(*NoticeRequest)(nil),           // 3: task_manager.notification.NoticeRequest
	(*NoticeResponse)(nil),          // 4: task_manager.notification.NoticeResponse
	(*NoticeEvent)(nil),             // 5: task_manager.notification.NoticeEvent
	(*WatchRequest)(nil),            // 6: task_manager.notification.WatchRequest
	(*GetNotifRequest)(nil),         // 7: task_manager.notification.GetNotifRequest
	(*common.Response)(nil),         // 8: task_manager.common.Response
}
var file_notifications_proto_depIdxs = []int32{
	0, // 0: task_manager.notification.Notification.event:type_name -> task_manager.notification.Event
	1, // 1: task_manager.notification.SendNotificationRequest.notification:type_name -> task_manager.notification.Notification
	8, // 2: task_manager.notification.NoticeResponse.response:type_name -> task_manager.common.Response
	2, // 3: task_manager.notification.NotificationService.SendNotification:input_type -> task_manager.notification.SendNotificationRequest
	3, // 4: task_manager.notification.NotificationService.PostToNoticeBoard:input_type -> task_manager.notification.NoticeRequest
	6, // 5: task_manager.notification.NotificationService.WatchNoticeBoard:input_type -> task_manager.notification.WatchRequest
	7, // 6: task_manager.notification.NotificationService.GetMyNotifications:input_type -> task_manager.notification.GetNotifRequest
	8, // 7: task_manager.notification.NotificationService.SendNotification:output_type -> task_manager.common.Response
	4, // 8: task_manager.notification.NotificationService.PostToNoticeBoard:output_type -> task_manager.notification.NoticeResponse
	5, // 9: task_manager.notification.NotificationService.WatchNoticeBoard:output_type -> task_manager.notification.NoticeEvent
	1, // 10: task_manager.notification.NotificationService.GetMyNotifications:output_type -> task_manager.notification.Notification
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_notifications_proto_init() }
func file_notifications_proto_init() {
	if File_notifications_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notifications_proto_rawDesc), len(file_notifications_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notifications_proto_goTypes,
		DependencyIndexes: file_notifications_proto_depIdxs,
		EnumInfos:         file_notifications_proto_enumTypes,
		MessageInfos:      file_notifications_proto_msgTypes,
	}.Build()
	File_notifications_proto = out.File
	file_notifications_proto_goTypes = nil
	file_notifications_proto_depIdxs = nil
}
