// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: task.proto

package task

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Priority int32

const (
	Priority_LOW    Priority = 0
	Priority_MEDIUM Priority = 1
	Priority_HIGH   Priority = 3
)

// Enum value maps for Priority.
var (
	Priority_name = map[int32]string{
		0: "LOW",
		1: "MEDIUM",
		3: "HIGH",
	}
	Priority_value = map[string]int32{
		"LOW":    0,
		"MEDIUM": 1,
		"HIGH":   3,
	}
)

func (x Priority) Enum() *Priority {
	p := new(Priority)
	*p = x
	return p
}

func (x Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_task_proto_enumTypes[0].Descriptor()
}

func (Priority) Type() protoreflect.EnumType {
	return &file_task_proto_enumTypes[0]
}

func (x Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Priority.Descriptor instead.
func (Priority) EnumDescriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

type Difficulty int32

const (
	Difficulty_NAHI_HAI_MUSHKIL       Difficulty = 0
	Difficulty_LAG_TO_MUSHKIL_RHA_HAI Difficulty = 1
	Difficulty_MUSHKIL_HAI            Difficulty = 2
	Difficulty_TUM_PE_NAHOGA          Difficulty = 3
	Difficulty_HUM_NA_PATO            Difficulty = 4
)

// Enum value maps for Difficulty.
var (
	Difficulty_name = map[int32]string{
		0: "NAHI_HAI_MUSHKIL",
		1: "LAG_TO_MUSHKIL_RHA_HAI",
		2: "MUSHKIL_HAI",
		3: "TUM_PE_NAHOGA",
		4: "HUM_NA_PATO",
	}
	Difficulty_value = map[string]int32{
		"NAHI_HAI_MUSHKIL":       0,
		"LAG_TO_MUSHKIL_RHA_HAI": 1,
		"MUSHKIL_HAI":            2,
		"TUM_PE_NAHOGA":          3,
		"HUM_NA_PATO":            4,
	}
)

func (x Difficulty) Enum() *Difficulty {
	p := new(Difficulty)
	*p = x
	return p
}

func (x Difficulty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Difficulty) Descriptor() protoreflect.EnumDescriptor {
	return file_task_proto_enumTypes[1].Descriptor()
}

func (Difficulty) Type() protoreflect.EnumType {
	return &file_task_proto_enumTypes[1]
}

func (x Difficulty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Difficulty.Descriptor instead.
func (Difficulty) EnumDescriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{1}
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      *Response              `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskResponse) GetResponse() *Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *CreateTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type UpdateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTaskRequest) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type UpdateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *Response              `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskResponse) Reset() {
	*x = UpdateTaskResponse{}
	mi := &file_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskResponse) ProtoMessage() {}

func (x *UpdateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTaskResponse) GetResp() *Response {
	if x != nil {
		return x.Resp
	}
	return nil
}

type GetTaskByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        int32                  `protobuf:"varint,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskByIdRequest) Reset() {
	*x = GetTaskByIdRequest{}
	mi := &file_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskByIdRequest) ProtoMessage() {}

func (x *GetTaskByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskByIdRequest.ProtoReflect.Descriptor instead.
func (*GetTaskByIdRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{4}
}

func (x *GetTaskByIdRequest) GetTaskID() int32 {
	if x != nil {
		return x.TaskID
	}
	return 0
}

type GetTaskByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskByIdResponse) Reset() {
	*x = GetTaskByIdResponse{}
	mi := &file_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskByIdResponse) ProtoMessage() {}

func (x *GetTaskByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskByIdResponse.ProtoReflect.Descriptor instead.
func (*GetTaskByIdResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{5}
}

func (x *GetTaskByIdResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskID        int32                  `protobuf:"varint,1,opt,name=taskID,proto3" json:"taskID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTaskRequest) GetTaskID() int32 {
	if x != nil {
		return x.TaskID
	}
	return 0
}

type DeleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *Response              `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTaskResponse) GetResp() *Response {
	if x != nil {
		return x.Resp
	}
	return nil
}

type ListAllTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllTasksRequest) Reset() {
	*x = ListAllTasksRequest{}
	mi := &file_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllTasksRequest) ProtoMessage() {}

func (x *ListAllTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllTasksRequest.ProtoReflect.Descriptor instead.
func (*ListAllTasksRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{8}
}

type ListAllTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllTasksResponse) Reset() {
	*x = ListAllTasksResponse{}
	mi := &file_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllTasksResponse) ProtoMessage() {}

func (x *ListAllTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllTasksResponse.ProtoReflect.Descriptor instead.
func (*ListAllTasksResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{9}
}

func (x *ListAllTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type CreateBulkTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBulkTaskRequest) Reset() {
	*x = CreateBulkTaskRequest{}
	mi := &file_task_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBulkTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBulkTaskRequest) ProtoMessage() {}

func (x *CreateBulkTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBulkTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateBulkTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{10}
}

func (x *CreateBulkTaskRequest) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type CreateBulkTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *Response              `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBulkTaskResponse) Reset() {
	*x = CreateBulkTaskResponse{}
	mi := &file_task_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBulkTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBulkTaskResponse) ProtoMessage() {}

func (x *CreateBulkTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBulkTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateBulkTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{11}
}

func (x *CreateBulkTaskResponse) GetResp() *Response {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *CreateBulkTaskResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_task_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{12}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Priority      Priority               `protobuf:"varint,4,opt,name=priority,proto3,enum=task_Manager.Priority" json:"priority,omitempty"`
	Difficulty    *Difficulty            `protobuf:"varint,5,opt,name=difficulty,proto3,enum=task_Manager.Difficulty,oneof" json:"difficulty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_task_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{13}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetPriority() Priority {
	if x != nil {
		return x.Priority
	}
	return Priority_LOW
}

func (x *Task) GetDifficulty() Difficulty {
	if x != nil && x.Difficulty != nil {
		return *x.Difficulty
	}
	return Difficulty_NAHI_HAI_MUSHKIL
}

var File_task_proto protoreflect.FileDescriptor

const file_task_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"task.proto\x12\ftask_Manager\";\n" +
	"\x11CreateTaskRequest\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.task_Manager.TaskR\x04task\"a\n" +
	"\x12CreateTaskResponse\x122\n" +
	"\bresponse\x18\x01 \x01(\v2\x16.task_Manager.ResponseR\bresponse\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\";\n" +
	"\x11UpdateTaskRequest\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.task_Manager.TaskR\x04task\"@\n" +
	"\x12UpdateTaskResponse\x12*\n" +
	"\x04resp\x18\x01 \x01(\v2\x16.task_Manager.ResponseR\x04resp\",\n" +
	"\x12GetTaskByIdRequest\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\x05R\x06taskID\"=\n" +
	"\x13GetTaskByIdResponse\x12&\n" +
	"\x04task\x18\x01 \x01(\v2\x12.task_Manager.TaskR\x04task\"+\n" +
	"\x11DeleteTaskRequest\x12\x16\n" +
	"\x06taskID\x18\x01 \x01(\x05R\x06taskID\"@\n" +
	"\x12DeleteTaskResponse\x12*\n" +
	"\x04resp\x18\x01 \x01(\v2\x16.task_Manager.ResponseR\x04resp\"\x15\n" +
	"\x13ListAllTasksRequest\"@\n" +
	"\x14ListAllTasksResponse\x12(\n" +
	"\x05tasks\x18\x01 \x03(\v2\x12.task_Manager.TaskR\x05tasks\"A\n" +
	"\x15CreateBulkTaskRequest\x12(\n" +
	"\x05tasks\x18\x01 \x03(\v2\x12.task_Manager.TaskR\x05tasks\"Z\n" +
	"\x16CreateBulkTaskResponse\x12*\n" +
	"\x04resp\x18\x01 \x01(\v2\x16.task_Manager.ResponseR\x04resp\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\">\n" +
	"\bResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd0\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x122\n" +
	"\bpriority\x18\x04 \x01(\x0e2\x16.task_Manager.PriorityR\bpriority\x12=\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\x0e2\x18.task_Manager.DifficultyH\x00R\n" +
	"difficulty\x88\x01\x01B\r\n" +
	"\v_difficulty*)\n" +
	"\bPriority\x12\a\n" +
	"\x03LOW\x10\x00\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x01\x12\b\n" +
	"\x04HIGH\x10\x03*s\n" +
	"\n" +
	"Difficulty\x12\x14\n" +
	"\x10NAHI_HAI_MUSHKIL\x10\x00\x12\x1a\n" +
	"\x16LAG_TO_MUSHKIL_RHA_HAI\x10\x01\x12\x0f\n" +
	"\vMUSHKIL_HAI\x10\x02\x12\x11\n" +
	"\rTUM_PE_NAHOGA\x10\x03\x12\x0f\n" +
	"\vHUM_NA_PATO\x10\x042\x88\x04\n" +
	"\vTaskService\x12O\n" +
	"\n" +
	"CreateTask\x12\x1f.task_Manager.CreateTaskRequest\x1a .task_Manager.CreateTaskResponse\x12O\n" +
	"\n" +
	"UpdateTask\x12\x1f.task_Manager.UpdateTaskRequest\x1a .task_Manager.UpdateTaskResponse\x12R\n" +
	"\vGetTaskById\x12 .task_Manager.GetTaskByIdRequest\x1a!.task_Manager.GetTaskByIdResponse\x12O\n" +
	"\n" +
	"DeleteTask\x12\x1f.task_Manager.DeleteTaskRequest\x1a .task_Manager.DeleteTaskResponse\x12[\n" +
	"\x0eCreateBulkTask\x12#.task_Manager.CreateBulkTaskRequest\x1a$.task_Manager.CreateBulkTaskResponse\x12U\n" +
	"\fListAllTasks\x12!.task_Manager.ListAllTasksRequest\x1a\".task_Manager.ListAllTasksResponseB8Z6github.com/Sourav-126/distributed-task-manager/pb/taskb\x06proto3"

var (
	file_task_proto_rawDescOnce sync.Once
	file_task_proto_rawDescData []byte
)

func file_task_proto_rawDescGZIP() []byte {
	file_task_proto_rawDescOnce.Do(func() {
		file_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)))
	})
	return file_task_proto_rawDescData
}

var file_task_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_task_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_task_proto_goTypes = []any{
	(Priority)(0),                  // 0: task_Manager.Priority
	(Difficulty)(0),                // 1: task_Manager.Difficulty
	(*CreateTaskRequest)(nil),      // 2: task_Manager.CreateTaskRequest
	(*CreateTaskResponse)(nil),     // 3: task_Manager.CreateTaskResponse
	(*UpdateTaskRequest)(nil),      // 4: task_Manager.UpdateTaskRequest
	(*UpdateTaskResponse)(nil),     // 5: task_Manager.UpdateTaskResponse
	(*GetTaskByIdRequest)(nil),     // 6: task_Manager.GetTaskByIdRequest
	(*GetTaskByIdResponse)(nil),    // 7: task_Manager.GetTaskByIdResponse
	(*DeleteTaskRequest)(nil),      // 8: task_Manager.DeleteTaskRequest
	(*DeleteTaskResponse)(nil),     // 9: task_Manager.DeleteTaskResponse
	(*ListAllTasksRequest)(nil),    // 10: task_Manager.ListAllTasksRequest
	(*ListAllTasksResponse)(nil),   // 11: task_Manager.ListAllTasksResponse
	(*CreateBulkTaskRequest)(nil),  // 12: task_Manager.CreateBulkTaskRequest
	(*CreateBulkTaskResponse)(nil), // 13: task_Manager.CreateBulkTaskResponse
	(*Response)(nil),               // 14: task_Manager.Response
	(*Task)(nil),                   // 15: task_Manager.Task
}
var file_task_proto_depIdxs = []int32{
	15, // 0: task_Manager.CreateTaskRequest.task:type_name -> task_Manager.Task
	14, // 1: task_Manager.CreateTaskResponse.response:type_name -> task_Manager.Response
	15, // 2: task_Manager.UpdateTaskRequest.task:type_name -> task_Manager.Task
	14, // 3: task_Manager.UpdateTaskResponse.resp:type_name -> task_Manager.Response
	15, // 4: task_Manager.GetTaskByIdResponse.task:type_name -> task_Manager.Task
	14, // 5: task_Manager.DeleteTaskResponse.resp:type_name -> task_Manager.Response
	15, // 6: task_Manager.ListAllTasksResponse.tasks:type_name -> task_Manager.Task
	15, // 7: task_Manager.CreateBulkTaskRequest.tasks:type_name -> task_Manager.Task
	14, // 8: task_Manager.CreateBulkTaskResponse.resp:type_name -> task_Manager.Response
	0,  // 9: task_Manager.Task.priority:type_name -> task_Manager.Priority
	1,  // 10: task_Manager.Task.difficulty:type_name -> task_Manager.Difficulty
	2,  // 11: task_Manager.TaskService.CreateTask:input_type -> task_Manager.CreateTaskRequest
	4,  // 12: task_Manager.TaskService.UpdateTask:input_type -> task_Manager.UpdateTaskRequest
	6,  // 13: task_Manager.TaskService.GetTaskById:input_type -> task_Manager.GetTaskByIdRequest
	8,  // 14: task_Manager.TaskService.DeleteTask:input_type -> task_Manager.DeleteTaskRequest
	12, // 15: task_Manager.TaskService.CreateBulkTask:input_type -> task_Manager.CreateBulkTaskRequest
	10, // 16: task_Manager.TaskService.ListAllTasks:input_type -> task_Manager.ListAllTasksRequest
	3,  // 17: task_Manager.TaskService.CreateTask:output_type -> task_Manager.CreateTaskResponse
	5,  // 18: task_Manager.TaskService.UpdateTask:output_type -> task_Manager.UpdateTaskResponse
	7,  // 19: task_Manager.TaskService.GetTaskById:output_type -> task_Manager.GetTaskByIdResponse
	9,  // 20: task_Manager.TaskService.DeleteTask:output_type -> task_Manager.DeleteTaskResponse
	13, // 21: task_Manager.TaskService.CreateBulkTask:output_type -> task_Manager.CreateBulkTaskResponse
	11, // 22: task_Manager.TaskService.ListAllTasks:output_type -> task_Manager.ListAllTasksResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_task_proto_init() }
func file_task_proto_init() {
	if File_task_proto != nil {
		return
	}
	file_task_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_proto_goTypes,
		DependencyIndexes: file_task_proto_depIdxs,
		EnumInfos:         file_task_proto_enumTypes,
		MessageInfos:      file_task_proto_msgTypes,
	}.Build()
	File_task_proto = out.File
	file_task_proto_goTypes = nil
	file_task_proto_depIdxs = nil
}
